### ISSUE TITLE
Chapter 5: TypeError: this.props.addToCart is not a function

### ISSUE THREAD

**Issue by elbination** [Apress/pro-react-16#26]
I got this error in ProductList.js:
`<button className="btn btn-success btn-sm float-right" onClick={ () => this.props.addToCart(p) }>`

=> TypeError: this.props.addToCart is not a function.

I've found some suggestions on SOF that we must take care of importing component but nothing works. What should I do?

**Comment by OriginalDrTone** [comment]
What did you do to solve the issue?

**Comment by JSalter2013** [comment]
Make sure your Shop.js file includes the addToCart attribute (Page 123 has a typography error - this line should really be marked as bold in the book);

				<div className="col-9 p-2">
					<ProductList products={ this.props.products } 
						**addToCart = { this.props.addToCart }**
					/>
				</div>
